# wercker version for box creation
box: amarburg/golang-ffmpeg:wheezy-1.8

# This is the build pipeline.
build:
  steps:
      ## So here's a kindof wierd point.  It needs a point to unpack the current
      #  repo, even though it's not Go and we never use it.
      # - setup-go-workspace:
      #         package-dir: github.com/amarburg/lazycache-deploy

      # Instead, we manually specify that we want to build a completely different go app..
      - script:
          name: Build Go application
          code: |
            export GOPATH=$HOME/go
            mkdir $GOPATH && cd $GOPATH
            go get github.com/amarburg/go-lazycache-app
            go install github.com/amarburg/go-lazycache-app

      - internal/docker-push:
        username: _json_key
        password: $GCR_JSON_KEY_FILE
        repository: gcr.io/smiling-gasket-155322/lazycache-deploy
        registry: https://gcr.io
        entrypoint: /root/go/bin/go-lazycache-app
        ports: "8080"
        tag: $WERCKER_GIT_COMMIT latest $WERCKER_GIT_BRANCH
        working-dir: $WERCKER_ROOT

      # Push completed builds to Docker hub
      - internal/docker-push:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
          repository: amarburg/lazycache-deploy
          entrypoint: /root/go/bin/go-lazycache-app
          ports: "8080"
          tag: $WERCKER_GIT_COMMIT latest $WERCKER_GIT_BRANCH
          working-dir: $WERCKER_ROOT
