version: '3'
services:
  lazycache:
    build: ../lazycache/
    ports:
      - "7080:8080"
    volumes:
      - /Users/aaron/workspace/go/src/github.com/amarburg/go-lazyfs-testfiles:/data
      - /tmp/image_store:/srv/image_store
    links:
      - nginx_data
      - nginx_image_store
  nginx_data:
    build: ../nginx_data/
    ports:
    - "7081:80"
    volumes:
      - /Users/aaron/workspace/go/src/github.com/amarburg/go-lazyfs-testfiles:/srv/data/:ro
  nginx_image_store:
    build: ../nginx_image_store/
    ports:
    - "7082:80"
    volumes:
      - /tmp/image_store:/srv/data:ro
