version: '3'
services:
  lazycache:
    build: lazycache/
    ports:
      - "7080:8080"
    volumes:
      - /data:/data
      - /home/amarburg/src/image_store:/srv/image_store
    links:
      - nginx-data
      - nginx-image-store
  nginx-data:
    build: nginx-data/
    ports:
    - "7081:80"
    volumes:
      - /home/amarburg/data:/srv/data:ro
  nginx-image-store:
    build: nginx-image-store/
    ports:
    - "7082:80"
    volumes:
      - /users/amarburg/src/image_store:/srv/image_store:ro
